const button= document.querySelector(".showme")
console.log(button)
console.log(document.querySelector("#pillado"))
console.log(document.querySelectorAll("p"))
console.log(document.querySelectorAll(".pokemon"))
const testme= document.querySelectorAll(`[data-function="testMe"]`)
console.log(testme)
 let hijo3= document.getElementById("Morty")
 console.log(hijo3)